-- 코드를 작성해주세요
SELECT INFO.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY
FROM ITEM_INFO AS INFO
WHERE NOT EXISTS (SELECT PARENT_ITEM_ID FROM ITEM_TREE AS TREE WHERE TREE.PARENT_ITEM_ID = INFO.ITEM_ID)
ORDER BY INFO.ITEM_ID DESC;