SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, 
       ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS I
JOIN REST_REVIEW AS R ON I.REST_ID = R.REST_ID  -- 1. JOIN을 먼저 하고
WHERE I.ADDRESS LIKE '서울%'                    -- 2. 그 다음 조건을 겁니다
GROUP BY I.REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC;