SELECT CASE 
        WHEN MONTH(E.DIFFERENTIATION_DATE) <= 3 THEN "1Q"
        WHEN MONTH(E.DIFFERENTIATION_DATE) > 3 AND MONTH(E.DIFFERENTIATION_DATE) <= 6 THEN "2Q"
        WHEN MONTH(E.DIFFERENTIATION_DATE) > 6 AND MONTH(E.DIFFERENTIATION_DATE) <= 9 THEN "3Q"
        WHEN MONTH(E.DIFFERENTIATION_DATE) > 9 THEN "4Q"
        END AS QUARTER,
        COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA AS E
GROUP BY QUARTER
ORDER BY QUARTER ASC;