-- 코드를 입력하세요
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C
INNER JOIN(CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H)
ON C.CAR_ID = H.CAR_ID AND CAR_TYPE = '세단'
WHERE H.START_DATE > '2022-09-30' AND H.START_DATE < '2022-11-01'
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC;
