SELECT FI.ID, NI.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
JOIN FISH_NAME_INFO NI
  ON FI.FISH_TYPE = NI.FISH_TYPE
WHERE (FI.FISH_TYPE, FI.LENGTH) IN (
    SELECT FI2.FISH_TYPE, MAX(FI2.LENGTH)
    FROM FISH_INFO FI2
    GROUP BY FI2.FISH_TYPE
)
ORDER BY FI.ID;