-- 코드를 작성해주세요


SELECT COUNT(I.ID) AS FISH_COUNT, 
       MAX(I.LENGTH) AS MAX_LENGTH, 
       I.FISH_TYPE AS FISH_TYPE
FROM FISH_INFO AS I
GROUP BY I.FISH_TYPE
HAVING AVG(IFNULL(I.LENGTH, 10)) >= 33
ORDER BY I.FISH_TYPE ASC;